### ISSUE TITLE
Carousel Slideshow - width incorrect when not visible on page load

### ISSUE THREAD

**Issue by emilycritter** [CodyHouse/cd-carousel-changelog#18]
### **Short description of the bug:** 
the carousel item width is not calculated correctly when the carousel is not visible on page load. In my particular case, the carousel is in a modal.

### **Steps to reproduce the bug:** 
1. add `carousel--slideshow` class to the carousel element
2. add the following styling:
```
.carousel--slideshow {
  --carousel-item-auto-size: 100%;
}
```
3. add a carousel to a modal
**Browser + Operating system:** NA, but I'm using Mac Chrome

### **Cause**
The issue is caused by this line in `_2_carousel.js`:
![image](https://user-images.githubusercontent.com/16456162/104346891-8d3fef00-54c5-11eb-8a0e-dbb4b817a3b8.png)

`itemStyle.getPropertyValue('width')` returns "100%", which is transformed to "100" by `parseFloat`

**Comment by claudia-romano** [comment]
Hi Emily,
the problem is not related to the `100%` value; if you hide your modal using a `display: none` and then initialise the carousel, the width of each item of the carousel is `0px` (since their ancestor is hidden). 

For example, I was able to include the carousel in the [CodyHouse Modal component](https://codyhouse.co/ds/components/app/full-screen-modal-window) with no issues:
https://www.dropbox.com/s/hlgdeyo7ujf5ctl/carousel-modal.mp4?dl=0

To fix the problem, you can either:
- Change the way your modal is hidden (e.g., we use `visibility: hidden; opacity: 0` for our modal component);
- Initialise the carousel once the modal is visible;
- Reset the carousel once the modal is open (you can do that triggering a 'resize' event on the window element).

Cheers
